services:
  app:
    image: badger-spill-api:latest
    container_name: badger-spill-api
    ports:
      - "${PORT}:${PORT}"
    restart: always
    environment:
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - PORT=${PORT}
      - BEHIND_REVERSE_PROXY=${BEHIND_REVERSE_PROXY}
