services:
  app:
    image: badger-spill-api:latest
    container_name: badger-spill-api
    ports:
      - "${PORT}:${PORT}"
    restart: always
    environment:
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - PORT=${PORT}
      - BEHIND_REVERSE_PROXY=${BEHIND_REVERSE_PROXY}
