services:
  app:
    image: badger-spill-api:latest
    container_name: badger-spill-api
    ports:
      - "443:443"
    restart: always
    environment:
      - TLS_KEY=${TLS_KEY}
      - TLS_CERT=${TLS_CERT}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
      - GMAIL_USERNAME=${GMAIL_USERNAME}
      - GMAIL_APP_PASS=${GMAIL_APP_PASS}
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
